In [11]:
import numpy as np
import sympy

In [30]:
#Usando numpy
A=np.array([[2,1,1],[0,1,-1],[0,2,4]])
B=np.array([[4,0,1],[-2,1,0],[-2,0,1]])
C,E=np.linalg.eig(A)
D,F=np.linalg.eig(B)
print(C,'\n',E)
print('\n',D,'\n',F)

[2. 2. 3.] 
 [[ 1.          0.         -0.40824829]
 [ 0.         -0.70710678  0.40824829]
 [ 0.          0.70710678 -0.81649658]]

 [1. 3. 2.] 
 [[ 0.          0.57735027 -0.33333333]
 [ 1.         -0.57735027  0.66666667]
 [ 0.         -0.57735027  0.66666667]]


In [31]:
#Usando sympy.
a=sympy.Matrix([[2,1,1],[0,1,-1],[0,2,4]])
b=sympy.Matrix([[4,0,1],[-2,1,0],[-2,0,1]])
c=a.eigenvects()
d = b.eigenvects()
print(c)
print('\n')
print(d)

[(2, 2, [Matrix([
[1],
[0],
[0]]), Matrix([
[ 0],
[-1],
[ 1]])]), (3, 1, [Matrix([
[ 1/2],
[-1/2],
[   1]])])]


[(1, 1, [Matrix([
[0],
[1],
[0]])]), (2, 1, [Matrix([
[-1/2],
[   1],
[   1]])]), (3, 1, [Matrix([
[-1],
[ 1],
[ 1]])])]


In [29]:
#Aplicandolo a nuestra matriz.
M=np.array([[949.4,-214.8,-285.4,223.8,-116.0],
            [-214.8,856.7,278.7,178.9,21.7],
            [-285.4,278.7,774.2,-133.6,119.2],
            [223.8,178.9,-133.6,660.4,125.6],
            [-116.0,21.7,119.2,125.6,529.8]])
m=sympy.Matrix([[949.4,-214.8,-285.4,223.8,-116.0],
            [-214.8,856.7,278.7,178.9,21.7],
            [-285.4,278.7,774.2,-133.6,119.2],
            [223.8,178.9,-133.6,660.4,125.6],
            [-116.0,21.7,119.2,125.6,529.8]])
eig1=np.linalg.eig(M)
eig2=m.eigenvects()
print(eig1)
print('\n')
print(eig2)

(array([1423.87022287,  952.47793813,  255.1750462 ,  543.38414076,
        595.59265203]), array([[ 0.65358365, -0.334368  ,  0.26581582, -0.55110382, -0.29436878],
       [-0.47524894, -0.61950498,  0.42049148,  0.22934626, -0.40117233],
       [-0.54944778, -0.01339861, -0.35287834, -0.74680931, -0.12522117],
       [ 0.15198733, -0.69405622, -0.60677934,  0.13182611,  0.33109898],
       [-0.14823575, -0.15006022,  0.50972991, -0.2618828 ,  0.79189703]]))


[(1423.87022287276, 1, [Matrix([
[ 0.653583652443316],
[-0.475248942298018],
[-0.549447782602716],
[   0.1519873274566],
[-0.148235753409995]])]), (952.477938131062, 1, [Matrix([
[-0.334368002855145],
[-0.619504975305932],
[-0.013398608838708],
[-0.694056216553123],
[-0.150060220521661]])]), (255.175046202679, 1, [Matrix([
[ 0.265815821310802],
[  0.42049147642663],
[-0.352878339353962],
[-0.606779336965511],
[ 0.509729910089551]])]), (543.384140764311, 1, [Matrix([
[ 0.551103820778062],
[-0.229346255438998],
[ 0.746809310848049